services:
  source_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: source_postgres_password
    volumes:
      - ./source_db/pgdata:/var/lib/postgresql/data
  target_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: target_postgres_password
    volumes:
      - ./target_db/pgdata:/var/lib/postgresql/data 
  
  pgadmin:
    image: dpage/pgadmin4
    user: "${UID}:${GID}"
    depends_on:
      - source_db
      - target_db
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin