services:
  source_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: source_postgres_password
    volumes:
      - ./source_db/pgdata:/var/lib/postgresql/data
      - ./source_db/scripts/dados_10_dias.csv:/dados_10_dias.csv
      - ./source_db/scripts/001_init_source_db.sh:/docker-entrypoint-initdb.d/001_init_source_db.sh
      - ./source_db/scripts/002_populate_source_db.sh:/docker-entrypoint-initdb.d/002_populate_source_db.sh

  target_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: target_postgres_password
    volumes:
      - ./target_db/pgdata:/var/lib/postgresql/data
      - ./target_db/scripts/001_init_target_db.sh:/docker-entrypoint-initdb.d/001_init_target_db.sh
  
  init_target_db:
    build:
      context: target_db/
    depends_on:
      - target_db
  
  source_db_api:
    build:
      context: source_db/
    ports:
      - 8000:8000
    env_file:
      - source_db/.env
    volumes:
      - ./source_db/src/:/app/src/
  
  dagster:
    build:
      context: etl/
    ports:
      - 3000:3000
    env_file:
      - etl/.env
    volumes:
      - ./etl/etl/:/app/etl/
    depends_on:
      - source_db
      - target_db
      - source_db_api
  docker_daemon:
    build:
      context: etl/
    entrypoint:
      - poetry
      - run
      - dagster-daemon
      - run
    container_name: docker_daemon
    restart: on-failure
    env_file:
      - etl/.env
    # environment:
    #   DAGSTER_POSTGRES_USER: "dagster_user"
    #   DAGSTER_POSTGRES_PASSWORD: "dagster_db_password"
    #   DAGSTER_POSTGRES_DB: "dagster"
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    # networks:
    #   - docker_example_network
    depends_on:
      - dagster
      - target_db


  
  pgadmin:
    image: dpage/pgadmin4
    user: "${UID}:${GID}"
    depends_on:
      - source_db
      - target_db
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin