services:
  source_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: source_postgres_password
    volumes:
      - ./source_db/pgdata:/var/lib/postgresql/data
      - ./source_db/dados_10_dias.csv:/dados_10_dias.csv
      - ./source_db/001_init_source_db.sh:/docker-entrypoint-initdb.d/001_init_source_db.sh
      - ./source_db/002_populate_source_db.sh:/docker-entrypoint-initdb.d/002_populate_source_db.sh

  target_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: target_postgres_password
    volumes:
      - ./target_db/pgdata:/var/lib/postgresql/data 
  
  pgadmin:
    image: dpage/pgadmin4
    user: "${UID}:${GID}"
    depends_on:
      - source_db
      - target_db
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin